return {
    -- Fe Gui
    { category = "Fe Gui", display = "B4krs Chat Bypasser", url = "https://raw.githubusercontent.com/BakaPraselol/v4lsB4krscbR/main/Loadstring%20version%20chat%20bypasser" },
    { category = "Fe Gui", display = "Comet", url = "https://raw.githubusercontent.com/FilteringEnabled/FE/main/Comet" },
    { category = "Fe Gui", display = "Epix's Fe Gui", url = "https://pastebin.com/raw/jMAwjKcb" },
    { category = "Fe Gui", display = "Energize [R6]", url = "https://pastebin.com/raw/1p6xnBNf" },
    { category = "Fe Gui", display = "Fex", url = "https://pastebin.com/raw/ES6xMCn7" },
    { category = "Fe Gui", display = "Free Gamepasses Gui", url = "https://pastebin.com/raw/QtQ4YnVR" },
    { category = "Fe Gui", display = "Free Gamepass Gui(dark modz)", url = "https://pastebin.com/raw/53yY1S39" },
    { category = "Fe Gui", display = "Nulware v3", url = "https://gist.githubusercontent.com/M6HqVBcddw2qaN4s/2d722888a388017c18028cd434c43a25/raw/dcccf1027fe4b90780e47767aaf584389c9d7771/EULma3fU90PUOKUn" },
    { category = "Fe Gui", display = "Player Orbit", url = "https://raw.githubusercontent.com/0Ben1/fe./main/Orbit%20GUI" },
    { category = "Fe Gui", display = "Tool Giver", url = "https://pastebin.com/raw/Ctqjmtkv" },
    { category = "Fe Gui", display = "Troll GUI", url = "https://pastebin.com/raw/nwGzXh1V" },
    { category = "Fe Gui", display = "Trolling Gui", url = "https://pastefy.app/ic5m4aJG/raw" },
    { category = "Fe Gui", display = "Xuctry FE Gui", url = "https://pastebin.com/raw/Zz4YDvLb" },

    -- Fe Script
    { category = "Fe Script", display = "Fe Anti Afk", url = "https://raw.githubusercontent.com/Nadir3709/Huubb/main/Mobile%20Scripting" },
    { category = "Fe Script", display = "Fe Anti Fall", url = "https://raw.githubusercontent.com/zephyr10101/AntiFall/main/Script" },
    { category = "Fe Script", display = "Fe Chat Bypasser", url = "https://raw.githubusercontent.com/bedra45/chetbypasser/main/chetbypass" },
    { category = "Fe Script", display = "Fe Chat Executor", url = "https://raw.githubusercontent.com/zephyr10101/chat-executor/main/chat-executor" },
    { category = "Fe Script", display = "Fe Chat Hack", url = "https://pastebin.com/raw/MBpnp3yS" },
    { category = "Fe Script", display = "Fe Chat Hax", url = "https://pastebin.com/raw/XFdQEjzx" },
    { category = "Fe Script", display = "Fe Clone", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_11l7Y131YqJjZ31QmV5L8pI23V02b3191sEg26E75472Wl78Vi8870jRv5txZyL1.lua.txt" },
    { category = "Fe Script", display = "Fe Collision", url = "https://raw.githubusercontent.com/0Ben1/fe/main/Collision.txt" },
    { category = "Fe Script", display = "Fe Control Npc", url = "https://pastefy.app/x8nWWq0M/raw" },
    { category = "Fe Script", display = "Fe Crawl Gui", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_vZDX8j5ggfAf58QhdJ59BVEmF6nmZgq4Mcjt2l8wn16CiStIW2P6EkNc605qv9K4.lua.txt" },
    { category = "Fe Script", display = "Fe Death Note", url = "https://pastefy.app/GoKxYBkU/raw" },
    { category = "Fe Script", display = "Fe Dino Fling", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_K2n31uc6t2wY5A8786eR4K15sgbUF0vdQ80a0LzgvLRkSNYd89H1AS3124gMR6SM.lua.txt" },
    { category = "Fe Script", display = "Fe Fling", url = "https://pastebin.com/raw/r97d7dS0" },
    { category = "Fe Script", display = "Fe Fling Gui", url = "https://raw.githubusercontent.com/fgasfga/Fe-Fling-GUI-For-roblox/main/Main.lua" },
    { category = "Fe Script", display = "Fe Flinger By GGH52Lan", url = "https://pastebin.com/raw/xu3C3TSU" },
    { category = "Fe Script", display = "Fe Freeze", url = "https://raw.githubusercontent.com/creepstu/fuzzy-octo-giggle/main/Source" },
    { category = "Fe Script", display = "Fe Gamepass Tool Giver v4", url = "https://pastefy.app/VYIAk3o1/raw" },
    { category = "Fe Script", display = "Fe Ghost", url = "https://pastebin.com/raw/uUtRsAX5" },
    { category = "Fe Script", display = "Fe God Mode | Obby", url = "https://raw.githubusercontent.com/zephyr10101/ignore-touchinterests/main/main" },
    { category = "Fe Script", display = "Fe Grab Parts", url = "https://pastefy.app/BbXuvVkK/raw" },
    { category = "Fe Script", display = "Fe Hat Spin", url = "https://pastebin.com/raw/32PbiWw1" },
    { category = "Fe Script", display = "Fe Invisible Boat", url = "https://pastefy.app/0CS5vmly/raw" },
    { category = "Fe Script", display = "Fe Ink Monster", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_f4i3ntKS5B8tK9zpCAnr31Dp7RNSYOo20gpln1fs1h2U4yjXNdNk6lFqZvN1Ft2p.lua.txt" },
    { category = "Fe Script", display = "Fe Invisible Script", url = "https://pastebin.com/raw/HrbT6bNK" },
    { category = "Fe Script", display = "Fe Invisibility Tool", url = "https://pastebin.com/raw/bdBWidBC" },
    { category = "Fe Script", display = "Fe Lag Switch", url = "https://raw.githubusercontent.com/0Ben1/fe/main/Protected%20-%202023-05-28T225112.055.lua.txt" },
    { category = "Fe Script", display = "Fe Parts Mover", url = "https://pastefy.app/Vcuyg09O/raw" },
    { category = "Fe Script", display = "Fe Punch", url = "https://pastefy.ga/GvnHVjT5/raw" },
    { category = "Fe Script", display = "Fe R15 to R6", url = "https://raw.githubusercontent.com/Imagnir/r6_anims_for_r15/main/r6_anims.lua" },
    { category = "Fe Script", display = "Fe Roll Ball", url = "https://pastebin.com/raw/BZr9bGDy" },
    { category = "Fe Script", display = "Fe SCP 173", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_nN0N66DHV2BjPwzYN59M17qSSlvJryM201CSC1sg07czxnZf48h9GHOFGd87G6Hh.lua.txt" },
    { category = "Fe Script", display = "Fe Spy", url = "https://raw.githubusercontent.com/GhostPlayer352/Test4/main/CCTV%20Camera" },
    { category = "Fe Script", display = "Fe Sword Kill All", url = "https://raw.githubusercontent.com/zephyr10101/sword-kill-all/main/script" },
    { category = "Fe Script", display = "Fe Touch Fling", url = "https://raw.githubusercontent.com/0Ben1/fe/main/obf_5wpM7bBcOPspmX7lQ3m75SrYNWqxZ858ai3tJdEAId6jSI05IOUB224FQ0VSAswH.lua.txt" },
    { category = "Fe Script", display = "Fe Tp Place Gui", url = "https://raw.githubusercontent.com/0Ben1/fe/main/Tp%20Place%20GUI" },
    { category = "Fe Script", display = "FE Yeet", url = "https://pastebin.com/raw/saMtiek2" },
    { category = "Fe Script", display = "Fe Zero Gravity Parts", url = "https://pastebin.com/raw/aXgyQyKY" },
    { category = "Fe Script", display = "Fe Zombie Fling", url = "https://pastefy.app/w7KnPY70/raw" },

    -- Not Sure Fe
    { category = "Not Sure Fe", display = "Among Us", url = "https://pastebin.com/raw/vNiNzr34" },
    { category = "Not Sure Fe", display = "Backflip", url = "https://pastebin.com/raw/n2gUwjc4" },
    { category = "Not Sure Fe", display = "Bloody Knife", url = "https://pastebin.com/raw/25P2tVPD" },
    { category = "Not Sure Fe", display = "Coolkid Gui", url = "https://pastebin.com/raw/YsVaUfYQ" },
    { category = "Not Sure Fe", display = "Gale Fighter", url = "https://pastebin.com/raw/YCH5P19e" },
    { category = "Not Sure Fe", display = "Psychopath", url = "https://pastebin.com/raw/9Lharw50" },
    { category = "Not Sure Fe", display = "Slasher", url = "https://pastebin.com/raw/sVEn1Tza" },
    { category = "Not Sure Fe", display = "Snake", url = "https://pastebin.com/raw/naRUdxrc" },
    { category = "Not Sure Fe", display = "Spider", url = "https://pastebin.com/raw/txsk1LJg" },

    -- Useful
    { category = "Useful", display = "Animation Gui", url = "https://raw.githubusercontent.com/GamingScripter/Animation-Hub/main/Animation%20Gui" },
    { category = "Useful", display = "Emotes Gui | Best", url = "https://gist.githubusercontent.com/RedZenXYZ/3da6af1961efa275de6c3c2a6dbace03/raw/bb027f99cec0ea48ef9c5eabfb9116ddff20633d/FE%2520Emotes%2520Gui" },
    { category = "Useful", display = "Emotes Gui", url = "https://pastebin.com/raw/fitjHU5J" },

    -- Sus Script
    { category = "Sus Script", display = "Pendulum Hub", url = "https://raw.githubusercontent.com/Tescalus/Pendulum-Hubs-Source/main/Pendulum%20Hub%20V5.lua" },
    { category = "Sus Script", display = "Sussy hub", url = "https://gist.githubusercontent.com/Nilrogram/8b0c8bd710be142f383c71f79279752c/raw/e4fb01a7de7cd498bb53270d2ad191dfab268a88/FE%2520SussyHub" }
}