return {
    -- Adopt Me
    { gameName = "Adopt Me", display = "Eazvy Hub", url = "https://raw.githubusercontent.com/Eazvy/Eazvy-Hub/main/GameLoader.lua" },
    { gameName = "Adopt Me", display = "Eclipse Hub", url = "https://api.eclipsehub.xyz/auth" },
    { gameName = "Adopt Me", display = "Ice Hub", url = "https://raw.githubusercontent.com/IceMael7/NewIceHub/main/Brookhaven" },
    { gameName = "Adopt Me", display = "Prodigy X", url = "https://gitfront.io/r/ReQiuYTPL/wFUydaK74uGx/hub/raw/ReQiuYTPLHub.lua" },
    { gameName = "Adopt Me", display = "Speed Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Script--Game/main/Script%20Game" },
    { gameName = "Adopt Me", display = "V.G Hub", url = "https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub" },

    -- All Star Tower Defense
    { gameName = "All Star Tower Defense", display = "KarmaPanda", url = "https://script.karmapanda.dev/" },
    { gameName = "All Star Tower Defense", display = "Trap Hub", url = "https://raw.githubusercontent.com/TrapstarKSSKSKSKKS/Main/main/TrapHub.lua" },

    -- Anime Adventures
    { gameName = "Anime Adventures", display = "Anime Adventures by Craymel02", url = "https://raw.githubusercontent.com/ArponAG/Scripts/main/AnimeAdventures.lua" },
    { gameName = "Anime Adventures", display = "Arpon Hub", url = "https://raw.githubusercontent.com/ArponAG/Scripts/main/AnimeAdventures_v2__Beta.lua" },
    { gameName = "Anime Adventures", display = "Crimson Hub", url = "https://raw.githubusercontent.com/TirSANX/CrimsonHUB/main/C_Loader" },
    { gameName = "Anime Adventures", display = "Keybrew Hub", url = "https://raw.githubusercontent.com/borntodiekuv/KeybrewHub/main/AA" },
    { gameName = "Anime Adventures", display = "Trap Hub", url = "https://raw.githubusercontent.com/TrapstarKSSKSKSKKS/Main/main/TrapHub.lua" },

    -- Anime Champions Simulator
    { gameName = "Anime Champions Simulator", display = "Banana Hub", url = "https://raw.githubusercontent.com/diepedyt/bui/main/temporynewkeysystem.lua" },
    { gameName = "Anime Champions Simulator", display = "Fazium Hub", url = "https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader" },
    { gameName = "Anime Champions Simulator", display = "HarPy", url = "https://raw.githubusercontent.com/xShadow1234/HarPy/main/HarPy_loader.lua" },
    { gameName = "Anime Champions Simulator", display = "Krzysztof Hub", url = "https://raw.githubusercontent.com/KrzysztofHub/script/main/loader.lua" },
    { gameName = "Anime Champions Simulator", display = "Muimi Hub", url = "https://raw.githubusercontent.com/bunny42312/script/main/acs" },
    { gameName = "Anime Champions Simulator", display = "Perfectus Hub", url = "https://raw.githubusercontent.com/PerfectusMim/Perfectus-Hub/main/perfectus-hub" },
    { gameName = "Anime Champions Simulator", display = "Sky Hub", url = "https://raw.githubusercontent.com/SKOIXLL/RIVERHUB-SKYHUB/main/WL.lua" },
    { gameName = "Anime Champions Simulator", display = "Yuto Hub", url = "https://raw.githubusercontent.com/Binintrozza/yutv2e/main/ACS" },

    -- Anime Dimensions
    { gameName = "Anime Dimensions", display = "Anime Ghost", url = "https://raw.githubusercontent.com/ghost-home/public/main/AnimeGhost.lua" },
    { gameName = "Anime Dimensions", display = "Bird Hub", url = "https://raw.githubusercontent.com/TheWitch-BirdHub/BirdHubv0.1/main/load" },
    { gameName = "Anime Dimensions", display = "Intruders", url = "https://raw.githubusercontent.com/lifaiossama/errors/main/Intruders.html" },
    { gameName = "Anime Dimensions", display = "Itachi", url = "https://raw.githubusercontent.com/destylol/masterhubv311/itachi/Main.lua" },

    -- Anime Fighters Simulator
    { gameName = "Anime Fighters Simulator", display = "Banana Hub", url = "https://raw.githubusercontent.com/diepedyt/bui/main/temporynewkeysystem.lua" },
    { gameName = "Anime Fighters Simulator", display = "Platinium Hub", url = "https://raw.githubusercontent.com/ZaRdoOx/Loader/main/PlatiniumLoader" },
    { gameName = "Anime Fighters Simulator", display = "SSJ3 Hub", url = "https://raw.githubusercontent.com/Gohan9k/ANFSnew/main/GOHANSSJ3" },
    { gameName = "Anime Fighters Simulator", display = "Yuto Hub", url = "https://raw.githubusercontent.com/Binintrozza/yutv2e/main/afss" },
    { gameName = "Anime Fighters Simulator", display = "Zer0 Hub", url = "https://raw.githubusercontent.com/Discord0000/Zer0Hub/main/MainScript.lua" },

    -- Anime Fighting Simulator X
    { gameName = "Anime Fighting Simulator X", display = "Blox Hub", url = "https://raw.githubusercontent.com/malicious-dev/RobloxScripting/main/AFSX.lua" },
    { gameName = "Anime Fighting Simulator X", display = "Muimi Hub", url = "https://raw.githubusercontent.com/bunnynwy/games/main/AnimeFightingX" },
    { gameName = "Anime Fighting Simulator X", display = "Project Nexus", url = "https://raw.githubusercontent.com/IkkyyDF/ProjectNexus/main/Loader.lua" },
    { gameName = "Anime Fighting Simulator X", display = "Sky Hub", url = "https://raw.githubusercontent.com/SKOIXLL/RIVERHUB-SKYHUB/main/WL.lua" },

    -- Anime Warriors Simulator 2
    { gameName = "Anime Warriors Simulator 2", display = "JumbleScripts", url = "https://jumblescripts.com/AnimeWarriorsSimulator2.lua" },
    { gameName = "Anime Warriors Simulator 2", display = "Verny Hub V2", url = "https://raw.githubusercontent.com/666dasdlolok/VernyHubV2/main/Main" },

    -- Arm Wrestler Simulator
    { gameName = "Arm Wrestler Simulator", display = "Flame Hub", url = "https://raw.githubusercontent.com/1Toxin/flame/main/loader" },
    { gameName = "Arm Wrestler Simulator", display = "HarPy", url = "https://raw.githubusercontent.com/xShadow1234/HarPy/main/script.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Kenniel", url = "https://raw.githubusercontent.com/Kenniel123/Arm-Wrestle-Simulator-Script/main/Arm-Wrestle-Simulator-Script" },
    { gameName = "Arm Wrestler Simulator", display = "LDS Hub", url = "https://raw.githubusercontent.com/limaspeedy/limaspeedy/main/HubLDS" },
    { gameName = "Arm Wrestler Simulator", display = "Legacy HandlesYT", url = "https://raw.githubusercontent.com/LOLking123456/arm7/main/wrestling" },
    { gameName = "Arm Wrestler Simulator", display = "Linear Hub", url = "https://raw.githubusercontent.com/yoolovr/Linear-Hub/main/loader.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Muimi Hub", url = "https://raw.githubusercontent.com/bunnynwy/games/main/main.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Nebula Hub", url = "https://raw.githubusercontent.com/Saitamahaah/SaitaHub/main/NebulaHub" },
    { gameName = "Arm Wrestler Simulator", display = "Pikachu Hub", url = "https://api.luarmor.net/files/v3/loaders/99d16edc79729a038994f85ce7335971.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Project WD", url = "https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Mainstring.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Screech Hub", url = "https://raw.githubusercontent.com/1Toxin/screech/main/AWS" },
    { gameName = "Arm Wrestler Simulator", display = "Skull Hub", url = "https://raw.githubusercontent.com/zicus-scripts/SkullHub/main/Loader.lua" },
    { gameName = "Arm Wrestler Simulator", display = "Spirit Hub", url = "https://raw.githubusercontent.com/zicus-scripts/gay-scripts/main/Loader.lua" },

    -- Arsenal
    { gameName = "Arsenal", display = "AdvanceTechV3", url = "https://raw.githubusercontent.com/YellowGreg/UltimateCromaSin-Arsenal-Gui/main/AdvanceTechV3.lua" },
    { gameName = "Arsenal", display = "Arsenal", url = "https://raw.githubusercontent.com/Infinity2346/Tect-Menu/main/Arsenalscript.txt" },
    { gameName = "Arsenal", display = "DarkHub", url = "https://raw.githubusercontent.com/RandomAdamYT/DarkHub/master/Init" },
    { gameName = "Arsenal", display = "Faded", url = "https://raw.githubusercontent.com/NighterEpic/Faded-Grid/main/YesEpic" },
    { gameName = "Arsenal", display = "F2b Hub", url = "https://raw.githubusercontent.com/F2B-HUB/F2B/main/HUB" },
    { gameName = "Arsenal", display = "OwlHub", url = "https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt" },
    { gameName = "Arsenal", display = "Tiger-Hub", url = "https://raw.githubusercontent.com/plutoguy/Tiger-Hub/main/loader.lua" },
    { gameName = "Arsenal", display = "V.Ghub", url = "https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub" },

    -- Bed Wars
    { gameName = "Bed Wars", display = "AURORA", url = "https://raw.githubusercontent.com/XStormDeveloper/AuroraForRoblox/main/lua" },
    { gameName = "Bed Wars", display = "IceCat", url = "https://github.com/Baconontop/bedwarsV2/raw/main/IcecatBedwars" },
    { gameName = "Bed Wars", display = "JH NN Gaming Bedwars V3.0", url = "https://pastebin.com/raw/2HNVwUvm" },
    { gameName = "Bed Wars", display = "Raven B4", url = "https://pastebin.com/raw/DzAdmNq1" },
    { gameName = "Bed Wars", display = "SOFT BED", url = "https://pastebin.com/raw/iWxWxX2M" },
    { gameName = "Bed Wars", display = "SNOW X V2", url = "https://raw.githubusercontent.com/uaahjajajqoqiqkqhwhwhw/SCRIPTERV3/main/SNOW%20X%20V2" },
    { gameName = "Bed Wars", display = "Future", url = "https://raw.githubusercontent.com/joeengo/Future/main/loadstring.lua" },
    { gameName = "Bed Wars", display = "Nightbed", url = "https://raw.githubusercontent.com/NTDCore/NightbedX/main/NightbedScriptLol/mostNightbed.lua" },
    { gameName = "Bed Wars", display = "Vape V4", url = "https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua" },
    { gameName = "Bed Wars", display = "Vezt(Private)", url = "https://raw.githubusercontent.com/VeztWare/Vezt/main/Vezt%20-%20BedWars%20(Private).lua" },
    { gameName = "Bed Wars", display = "Xrayon", url = "https://raw.githubusercontent.com/dorukqpx/Xrayon/main/xrayonv2.lua" },

    -- Bee Swarm Simulator
    { gameName = "Bee Swarm Simulator", display = "Blue Hub", url = "https://raw.githubusercontent.com/scriptpastebin/raw/main/29" },
    { gameName = "Bee Swarm Simulator", display = "Cloud Hub", url = "https://raw.githubusercontent.com/BadScripters/CloudHub/main/hub" },
    { gameName = "Bee Swarm Simulator", display = "Histy Hub", url = "https://raw.githubusercontent.com/scriptpastebin/raw/main/Histy" },
    { gameName = "Bee Swarm Simulator", display = "Kometa Hub", url = "https://s.kometa.pw/kometa.lua" },
    { gameName = "Bee Swarm Simulator", display = "Macro Hub", url = "https://www.macrov2-script.xyz/macrov2.lua" },
    { gameName = "Bee Swarm Simulator", display = "Pepsi Swarm", url = "rbxassetid://4384103988" },

    -- Blade Ball
    { gameName = "Blade Ball", display = "Alchemy Hub", url = "https://alchemyhub.xyz/v2" },
    { gameName = "Blade Ball", display = "AlSploit", url = "https://raw.githubusercontent.com/AlSploit/AlSploit/main/BladeBall" },
    { gameName = "Blade Ball", display = "Artis Z", url = "https://raw.githubusercontent.com/lightHubDev/ArtisZ/a6dd81c647a4b4a51b0ecee8fb868472d45eacad/Artis Z Main" },
    { gameName = "Blade Ball", display = "Auto Parry by FFJ", url = "https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/autoparry.lua" },
    { gameName = "Blade Ball", display = "Bedol Hub", url = "https://raw.githubusercontent.com/nqxlOfc/Loaders/main/Blade_Ball.lua" },
    { gameName = "Blade Ball", display = "Berserk Hub", url = "https://raw.githubusercontent.com/samirayt/Whitelist/main/Whitelist%20Pago" },
    { gameName = "Blade Ball", display = "Blade Ball", url = "https://pastebin.com/raw/qxA2ETxy" },
    { gameName = "Blade Ball", display = "Darkrai Hub", url = "https://raw.githubusercontent.com/DenDenZYT/DenDenZ-On-YouTube/main/Script%20Collection" },
    { gameName = "Blade Ball", display = "Del Hub", url = "https://pastebin.com/raw/ADjr564T" },
    { gameName = "Blade Ball", display = "EminX Hub", url = "https://raw.githubusercontent.com/EminenceXLua/Blade-your-Balls/main/BladeBallLoader.lua" },
    { gameName = "Blade Ball", display = "Freya Hub", url = "https://pastefy.app/qpzOA8ZR/raw" },
    { gameName = "Blade Ball", display = "Fuji Hub", url = "https://shz.al/~main/dread/Fuji-Hub/script" },
    { gameName = "Blade Ball", display = "Galaxy Hub", url = "https://pastebin.com/raw/fruEwHqY" },
    { gameName = "Blade Ball", display = "Hexa Hub", url = "https://raw.githubusercontent.com/Brothinkimnoob/AUTO-PARRY-HEXA-V3/main/HEXA%20V3" },
    { gameName = "Blade Ball", display = "Lightux Hub", url = "https://raw.githubusercontent.com/zeuise0002/SSSWWW222/main/README.md" },
    { gameName = "Blade Ball", display = "Ln Hub", url = "https://raw.githubusercontent.com/No6No6No7yt/Lumin-Hub/main/BladeV4.lua" },
    { gameName = "Blade Ball", display = "Luy Hub", url = "https://shz.al/~LUYHUB" },
    { gameName = "Blade Ball", display = "Mynhub", url = "https://raw.githubusercontent.com/Nextix1/MYNHUB/main/BLADEBALL" },
    { gameName = "Blade Ball", display = "Neo.x", url = "https://raw.githubusercontent.com/DomainXV3/NEO.X/main/Velocity.lua" },
    { gameName = "Blade Ball", display = "Neptune Hub", url = "https://raw.githubusercontent.com/TopPlayzYT/BladeBall/main/open" },
    { gameName = "Blade Ball", display = "Neva Hub", url = "https://raw.githubusercontent.com/VEZ2/NEVAHUB/main/2" },
    { gameName = "Blade Ball", display = "Nextix Hub", url = "https://raw.githubusercontent.com/Nextix1/Nextix-Hub/main/Loader" },
    { gameName = "Blade Ball", display = "Nexus", url = "https://raw.githubusercontent.com/s-o-a-b/nexus/main/loadstring" },
    { gameName = "Blade Ball", display = "Noob", url = "https://pastebin.com/raw/sYWb0Uin" },
    { gameName = "Blade Ball", display = "Nova x Fusion Hub", url = "https://pastefy.app/xOAWDWaA/raw" },
    { gameName = "Blade Ball", display = "OMG Hub", url = "https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua" },
    { gameName = "Blade Ball", display = "Oxox Hub", url = "https://raw.githubusercontent.com/Krnow1/Bladeball_g/main/Credits_krnow" },
    { gameName = "Blade Ball", display = "Prolex", url = "https://paste.gg/p/anonymous/1734a4ee207844b994df2f36157afacd/files/1e79ac12fc8a47ef8263d5e9d43b7137/raw" },
    { gameName = "Blade Ball", display = "R4mpage V4", url = "https://paste.gg/p/anonymous/c2ba80c243e04cdaba2926ef0b747d9d/files/4471c9e60f444ebb98927dc25c52e8c7/raw" },
    { gameName = "Blade Ball", display = "Raven B4", url = "https://pastebin.com/raw/DzAdmNq1" },
    { gameName = "Blade Ball", display = "REDz HUB", url = "https://raw.githubusercontent.com/REDzHUB/BladeBall/main/eng" },
    { gameName = "Blade Ball", display = "SaZx HubZ", url = "https://pastefy.app/0r7T66Gx/raw" },
    { gameName = "Blade Ball", display = "ScriptX", url = "https://raw.githubusercontent.com/JunBloxYTPlayz/Blade-Ball-Working-Most-Latest/main/Blade%20Ball%20Script%20X%20v1" },
    { gameName = "Blade Ball", display = "Sirius", url = "https://raw.githubusercontent.com/xdevslasher/Siriusisbetter/main/xyz.bb.lua" },
    { gameName = "Blade Ball", display = "Stellar Hub", url = "https://raw.githubusercontent.com/ImNotFatBitch/LoaderScripts/main/LoaderScripts" },
    { gameName = "Blade Ball", display = "Symphony Hub", url = "https://itsjidy.github.io/SymphonyHub/Loader.html" },
    { gameName = "Blade Ball", display = "THub", url = "https://raw.githubusercontent.com/tibe0124/tibe0124/main/Thub-blade-ur-balls" },
    { gameName = "Blade Ball", display = "Visual", url = "https://raw.githubusercontent.com/DevTravDYT/VisualProductV10/main/KeySystem/ThankForUsing!/by-d-e-v-t-r-a-v/lua" },
    { gameName = "Blade Ball", display = "Visualize", url = "https://raw.githubusercontent.com/lamabosku2/futurecome/main/fu3kcardmoly" },
    { gameName = "Blade Ball", display = "White Hub", url = "https://pastebin.com/raw/E07Wyg7L" },
    { gameName = "Blade Ball", display = "Wii Hub", url = "https://raw.githubusercontent.com/lamabosku2/futurecome/main/fu3kcardmoly" },
    { gameName = "Blade Ball", display = "xyz.beta", url = "https://raw.githubusercontent.com/xdevslasher/xyz.BB/main/xyz.bb.lua" },
    { gameName = "Blade Ball", display = "Ysacxy Hub", url = "https://pastebin.com/raw/Hqr4NnFU" },
    { gameName = "Blade Ball", display = "Zap Hub", url = "https://zaphub.xyz/Exec" },
    { gameName = "Blade Ball", display = "Zen.cc", url = "https://raw.githubusercontent.com/xdevslasher/zen.cc/main/zenultramax.lua" },

    -- Bloxburg
    { gameName = "Bloxburg", display = "BloxBurger", url = "https://bloxburger.eu/scripts/free/script.lua" },
    { gameName = "Bloxburg", display = "Evo v4", url = "https://projectevo.xyz/v4/script.lua" },
    { gameName = "Bloxburg", display = "Vysor", url = "https://api.luarmor.net/files/v3/loaders/2f213cf4f330b8eb17423eaa4ae64ff6.lua" },

    -- Blox Fruit (full list from your code)
    { gameName = "Blox Fruit", display = "Alchemy Hub", url = "https://alchemyhub.xyz/v2" },
    { gameName = "Blox Fruit", display = "Apple Hub", url = "https://raw.githubusercontent.com/ImTienNguyenZ/AppleHub/main/LoaderBF" },
    { gameName = "Blox Fruit", display = "Atomic Hub", url = "https://raw.githubusercontent.com/ArceusXHub/atomic-hub/main/atomic-hub.lua" },
    { gameName = "Blox Fruit", display = "Beo Hub", url = "https://raw.githubusercontent.com/Bestxemchua/agagagaq/main/BeoHUB/BeoHUB.lua" },
    { gameName = "Blox Fruit", display = "Blck Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/BLCK" },
    { gameName = "Blox Fruit", display = "BlackTrap", url = "https://blacktrap.org/blacktrap/users/checkpoint/Auth.txt" },
    { gameName = "Blox Fruit", display = "Bull Hub", url = "https://raw.githubusercontent.com/Fiend1sh/FiendMain/main/BullMain" },
    { gameName = "Blox Fruit", display = "CFrame Hub", url = "https://raw.githubusercontent.com/Steveee11/Scripts/main/Blox%20Fruits%20OP%20Script" },
    { gameName = "Blox Fruit", display = "Cokka Hub", url = "https://codeberg.org/CokkaHub/Loadstring/raw/branch/main/CokkaHub.lua" },
    { gameName = "Blox Fruit", display = "Destiny Hub", url = "https://raw.githubusercontent.com/KudoCon/DestinyHub/main/DestinyKey" },
    { gameName = "Blox Fruit", display = "Domadic Hub", url = "https://raw.githubusercontent.com/Domadicoof/Domadicoof/main/Domadichub/NottoGay/Start.ranscript" },
    { gameName = "Blox Fruit", display = "Dynamic Hub", url = "https://Dynamic.xcodehoster.com/loader.lua" },
    { gameName = "Blox Fruit", display = "Ez Beli", url = "https://raw.githubusercontent.com/NickelHUBB/SonicTuru/main/ChestFarmOp" },
    { gameName = "Blox Fruit", display = "Fao Hub", url = "https://raw.githubusercontent.com/PNguyen0199/Script/main/Fai-Fao.lua" },
    { gameName = "Blox Fruit", display = "Flare Hub", url = "https://raw.githubusercontent.com/1f0yt/community/master/flares" },
    { gameName = "Blox Fruit", display = "FTS V2", url = "https://raw.githubusercontent.com/Tulam2000/FTS-HUB/main/FTS%20x%20Hub" },
    { gameName = "Blox Fruit", display = "Gringo Hub", url = "https://github.com/LeVanNhatIT/GringoHub/raw/main/Loading_Ui/Loading" },
    { gameName = "Blox Fruit", display = "Halo X Hub", url = "https://raw.githubusercontent.com/HALOxHUB/ScriptLoader/main/Loader.lua" },
    { gameName = "Blox Fruit", display = "Hoho Hub", url = "https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI" },
    { gameName = "Blox Fruit", display = "Hung Hub", url = "https://raw.githubusercontent.com/hungquan99/HungHub/main/Loading" },
    { gameName = "Blox Fruit", display = "JJTx Hub", url = "https://raw.githubusercontent.com/JJTChannel/JJTxHUB/main/Re-come.lua" },
    { gameName = "Blox Fruit", display = "Law Hub", url = "https://raw.githubusercontent.com/BestScriptEverr/Main-/main/Law%20hub" },
    { gameName = "Blox Fruit", display = "Madox Hub", url = "https://raw.githubusercontent.com/Fiend1sh/FiendMain/main/MadoxHubKey" },
    { gameName = "Blox Fruit", display = "Makima Hub", url = "https://raw.githubusercontent.com/Piwwy0909/MakimaRemake/main/Cumback.Makima" },
    { gameName = "Blox Fruit", display = "Makori Hub", url = "https://raw.githubusercontent.com/Domadicoof/Domadicoof/main/NewHubX.txt" },
    { gameName = "Blox Fruit", display = "Master Hub", url = "https://raw.githubusercontent.com/onepicesenpai/onepicesenpai/main/onichanokaka" },
    { gameName = "Blox Fruit", display = "Mama Hub", url = "https://raw.githubusercontent.com/MAMAhub1/Mmahub/main/README.md" },
    { gameName = "Blox Fruit", display = "MeMayBeo", url = "https://raw.githubusercontent.com/ZPSXHUB/Z/main/MeMayBeo" },
    { gameName = "Blox Fruit", display = "Modz Hub", url = "https://raw.githubusercontent.com/1f0yt/community/master/modz" },
    { gameName = "Blox Fruit", display = "MTriet Hub", url = "https://raw.githubusercontent.com/Minhtriettt/Free-Script/main/MTriet-Hub.lua" },
    { gameName = "Blox Fruit", display = "Mukuro Hub", url = "https://raw.githubusercontent.com/xDepressionx/Free-Script/main/BloxFruit.lua" },
    { gameName = "Blox Fruit", display = "Nexuz Hub", url = "https://raw.githubusercontent.com/NexuzHub/Main-/main/Script" },
    { gameName = "Blox Fruit", display = "Neva Hub", url = "https://raw.githubusercontent.com/VEZ2/NEVAHUB/main/2" },
    { gameName = "Blox Fruit", display = "Night Hub", url = "https://raw.githubusercontent.com/NIGHTHUBONTOP/Main/main/NIGHT-HUB" },
    { gameName = "Blox Fruit", display = "Omg Hub", url = "https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua" },
    { gameName = "Blox Fruit", display = "Pado Hub", url = "https://raw.githubusercontent.com/REWzaKunGz1/premium/main/PadoHub" },
    { gameName = "Blox Fruit", display = "Raito Hub", url = "https://raw.githubusercontent.com/Efe0626/RaitoHub/main/Script" },
    { gameName = "Blox Fruit", display = "Rblx Hub", url = "https://paste.xyzo.space/rblxhub/all.lua" },
    { gameName = "Blox Fruit", display = "REDzHUB", url = "https://raw.githubusercontent.com/REDzHUB/BloxFruits/main/redz9999.lua" },
    { gameName = "Blox Fruit", display = "Sagi Hub", url = "https://raw.githubusercontent.com/BestScriptEverr/Main-/main/SagiHub" },
    { gameName = "Blox Fruit", display = "Saki Hub", url = "https://sharetext.me/raw/u3if6m3hgr" },
    { gameName = "Blox Fruit", display = "Sara Hub", url = "https://raw.githubusercontent.com/SaraSenpai/bloxfruist/main/Sarahub" },
    { gameName = "Blox Fruit", display = "Secret Hub", url = "https://raw.githubusercontent.com/FtsHub/main/main/SecretHub.Lua" },
    { gameName = "Blox Fruit", display = "Snow Hub", url = "https://raw.githubusercontent.com/ZPSXHUB/Hub/main/SnowHub-BloxFruit" },
    { gameName = "Blox Fruit", display = "Sonic Hub", url = "https://raw.githubusercontent.com/NickelHUBB/SonicTuru/main/Protected-25.lua" },
    { gameName = "Blox Fruit", display = "Speed Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Speed-Hub-X/main/SpeedHubX" },
    { gameName = "Blox Fruit", display = "Switch Hub", url = "https://raw.githubusercontent.com/Augustzyzx/UraniumX/main/src_.lua.txt" },
    { gameName = "Blox Fruit", display = "T7GFY", url = "https://raw.githubusercontent.com/minded102/dokinbog/main/README.md" },
    { gameName = "Blox Fruit", display = "Tawan Hub", url = "https://raw.githubusercontent.com/kill55547/TAWAN_HUB/main/TAWANxHUB_V2.lua.txt" },
    { gameName = "Blox Fruit", display = "TNG Hub", url = "https://raw.githubusercontent.com/tngaming123/TNGHub/main/AutoRaceV4.lua" },
    { gameName = "Blox Fruit", display = "Thunder Z", url = "https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader" },
    { gameName = "Blox Fruit", display = "Turbo Hub", url = "https://gitlab.com/turbohubz/loader.xyz/loader/-/raw/main/TurboHub-Loader" },
    { gameName = "Blox Fruit", display = "Uranium Hub", url = "https://raw.githubusercontent.com/Augustzyzx/UraniumMobile/main/UraniumKak.lua" },
    { gameName = "Blox Fruit", display = "Vector Hub", url = "https://raw.githubusercontent.com/Tuxoz/VectorHub/main/MBPC" },
    { gameName = "Blox Fruit", display = "Void Hub", url = "https://raw.githubusercontent.com/Efe0626/VoidHub/main/Script" },
    { gameName = "Blox Fruit", display = "Winnable Hub", url = "https://raw.githubusercontent.com/xlostpexz/tyuiop/Fps/Loading.lua" },
    { gameName = "Blox Fruit", display = "Xenon Hub", url = "https://raw.githubusercontent.com/Larinax999/leak/main/khemtitgamerHUB-BF.lua" },
    { gameName = "Blox Fruit", display = "Zamex Hub", url = "https://raw.githubusercontent.com/Sixnumz/ZamexMobile/main/Zamex_Mobile.lua" },
    { gameName = "Blox Fruit", display = "Zaque Hub", url = "https://raw.githubusercontent.com/Mei2232/ZaqueHub/main/Zaque%20Hub" },
    { gameName = "Blox Fruit", display = "Zaque Hub(PC)", url = "https://raw.githubusercontent.com/ZaqueHub/BloxFruitPC/main/Protected.lua" },
    { gameName = "Blox Fruit", display = "Zee Hub", url = "https://zKuzy.link/ZeeHub.lua" },
    { gameName = "Blox Fruit", display = "Zekrom Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Zekrom-Hub-X/main/Zekrom-Hub-X-exe" },
    { gameName = "Blox Fruit", display = "Zen Hub", url = "https://raw.githubusercontent.com/ZenHubTheBest/Main/main/Loader" },

    -- Break In 2
    { gameName = "Break In 2", display = "Breaking Blitz", url = "https://raw.githubusercontent.com/RScriptz/RobloxScripts/main/BreakIn2.lua" },
    { gameName = "Break In 2", display = "Break In 2 Kavo", url = "https://raw.githubusercontent.com/danielontopp/scripts/main/77_OCM25E2M.lua.txt" },
    { gameName = "Break In 2", display = "Break In 2 Orion", url = "https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua" },
    { gameName = "Break In 2", display = "Camping Trip", url = "https://raw.githubusercontent.com/yieviro92creepy/Testfu/main/Breakin2" },
    { gameName = "Break In 2", display = "D8rk Hub", url = "https://raw.githubusercontent.com/D8rkX/D8rk-Hub/main/Games/Break%20In%202.lua" },
    { gameName = "Break In 2", display = "F Hub", url = "https://raw.githubusercontent.com/memejames/Hide/main/Break%20in%202" },
    { gameName = "Break In 2", display = "IceWare", url = "https://raw.githubusercontent.com/RScriptz/RobloxScripts/main/BreakIn2.lua" },
    { gameName = "Break In 2", display = "Jn Hh Gaming", url = "https://freenote.biz/raw/ScmsS7SwTW" },
    { gameName = "Break In 2", display = "Legend HandlesYT", url = "https://raw.githubusercontent.com/LOLking123456/Break/main/In" },
    { gameName = "Break In 2", display = "Playvora + JNHH Hub", url = "https://freenote.biz/raw/80jXm2Q0a7" },

    -- Build A Boat
    { gameName = "Build A Boat", display = "Astra Hub", url = "https://pastebin.com/raw/0YezNNRh" },
    { gameName = "Build A Boat", display = "Auto Build", url = "https://raw.githubusercontent.com/max2007killer/auto-build-not-limit/main/autobuild.txt" },
    { gameName = "Build A Boat", display = "Buil a boat for treasure", url = "https://raw.githubusercontent.com/XRoLLu/UWU/main/BUILD%20A%20BOAT%20FOR%20TREASURE.lua" },
    { gameName = "Build A Boat", display = "Eclipse Hub", url = "https://api.eclipsehub.xyz/auth" },
    { gameName = "Build A Boat", display = "NooVster", url = "https://raw.githubusercontent.com/NooVster/v1.1/main/Source" },
    { gameName = "Build A Boat", display = "Ruby Hub", url = "https://raw.githubusercontent.com/Deni210/BABFT/main/Ruby%20Hub" },
    { gameName = "Build A Boat", display = "Space Hub", url = "https://raw.githubusercontent.com/Lucasfin000/SpaceHub/main/spacvehubloader" },
    { gameName = "Build A Boat", display = "Thunder Z", url = "https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader" },
    { gameName = "Build A Boat", display = "Vynixius 2.0", url = "https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Loader.lua" },
    { gameName = "Build A Boat", display = "Zolars X", url = "https://raw.githubusercontent.com/VIPFirstTime/UploadFile/main/Protected_8627265294288055.lua" },

    -- Chaos
    { gameName = "Chaos", display = "AstralHub", url = "https://raw.githubusercontent.com/Vcsk/AstralHub/main/Loader.lua" },
    { gameName = "Chaos", display = "Bad Hub", url = "https://raw.githubusercontent.com/idkfffff/MainScript/main/BadHub.lua" },
    { gameName = "Chaos", display = "Chaos Script", url = "https://raw.githubusercontent.com/1111-ssss/Chaos_Script/main/Chaos_script.txt" },
    { gameName = "Chaos", display = "SlapX Chaos Gui", url = "https://raw.githubusercontent.com/Slinzo1/Chao-s-/main/Chaos" },
    { gameName = "Chaos", display = "Juanko Hub v4", url = "https://pastebin.com/raw/VzPbD7GW" },
    { gameName = "Chaos", display = "Ro Flux", url = "https://roflux.net/scripts/games/" .. tostring(game.PlaceId) .. ".lua" },
    { gameName = "Chaos", display = "TSSChaosScript", url = "https://raw.githubusercontent.com/Idkwhatudoin/TSS/main/TSSChaosScript" },
    { gameName = "Chaos", display = "Chaos Gui", url = "https://raw.githubusercontent.com/aidanlolol/MainScript/main/ChaosScriptVersionTwoPointOne.lua" },

    -- Color Or Die
    { gameName = "Color Or Die", display = "Color 0r Die | YT ToraIsMe", url = "https://raw.githubusercontent.com/ToraIsMe/ToraIsMe/main/0color" },
    { gameName = "Color Or Die", display = "Now Mon", url = "https://raw.githubusercontent.com/NoWMoN/Color-0r-DIE/main/NoWMoN.lua" },

    -- Combat Warriors
    { gameName = "Combat Warriors", display = "Cwhb", url = "https://raw.githubusercontent.com/IsaaaKK/cwhb/main/cw.txt" },
    { gameName = "Combat Warriors", display = "Hydra Ui", url = "https://raw.githubusercontent.com/CheeseOnGithub/cheese-hook/main/main%20hydra%20ui.lua" },
    { gameName = "Combat Warriors", display = "Nova Hub", url = "https://raw.githubusercontent.com/SussyImposterRed/Scripts/main/NOVA_HUB_SOURCE" },
    { gameName = "Combat Warriors", display = "Project-Hook", url = "https://raw.githubusercontent.com/SpiritXmas/Project-Hook/main/required.lua" },
    { gameName = "Combat Warriors", display = "Zap Hub", url = "https://www.itots.tk/zaphub/combat-warriors.lua" },

    -- Da Hood
    { gameName = "Da Hood", display = "DaHub", url = "https://raw.githubusercontent.com/NoUGotbannedlol/DaHubV3/main/Launch" },
    { gameName = "Da Hood", display = "DragonWare", url = "https://paste-drop.com/raw/ZAE0Or8c3y" },
    { gameName = "Da Hood", display = "Enclosed", url = "https://raw.githubusercontent.com/dylannpro123/enclosed/main/enclosed" },
    { gameName = "Da Hood", display = "Focus", url = "https://pastebin.com/raw/5BkTV67C" },
    { gameName = "Da Hood", display = "Lanxility", url = "https://raw.githubusercontent.com/cjdjmj/new-ui-godmode/main/README.md" },
    { gameName = "Da Hood", display = "OxHub", url = "https://raw.githubusercontent.com/patrickhackplus/oxhub/main/kidsinmybasement" },
    { gameName = "Da Hood", display = "Pluto", url = "https://raw.githubusercontent.com/Scrvpter/Pluto/Lua/Loader.Lua" },
    { gameName = "Da Hood", display = "RayX", url = "https://raw.githubusercontent.com/SpaceYes/Lua/Main/DaHood.Lua" },
    { gameName = "Da Hood", display = "Serenity", url = "https://raw.githubusercontent.com/cypherdh/Serenity/main/script" },
    { gameName = "Da Hood", display = "Space Hub", url = "https://raw.githubusercontent.com/Lucasfin000/SpaceHub/main/SpaceHubLoader" },
    { gameName = "Da Hood", display = "Space X", url = "https://raw.githubusercontent.com/spacexrandom/Lua/main/DaHood" },
    { gameName = "Da Hood", display = "SwagMode", url = "https://raw.githubusercontent.com/lerkermer/lua-projects/master/SwagModeV002" },
    { gameName = "Da Hood", display = "Vortex", url = "https://raw.githubusercontent.com/ImagineProUser/vortexdahood/main/vortex" },
    { gameName = "Da Hood", display = "Zapped", url = "https://ekso.gq/raw/relases/zapped.lua" },
    { gameName = "Da Hood", display = "Zinc Hub", url = "https://raw.githubusercontent.com/Zinzs/luascripting/main/canyoutellitsadahoodscriptornot.lua" },

    -- Doors
    { gameName = "Doors", display = "Black Hub", url = "https://raw.githubusercontent.com/scriptpastebin/raw/main/Doors" },
    { gameName = "Doors", display = "DarkCheatClient", url = "https://raw.githubusercontent.com/VaniaPerets/FolderGui-FolderHub/main/loader.lua" },
    { gameName = "Doors", display = "Darkrai X", url = "https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/Doors" },
    { gameName = "Doors", display = "Dxrk Hub", url = "https://raw.githubusercontent.com/CreepyPSC/dxrkhub/main/doors-scripts/hub-source" },
    { gameName = "Doors", display = "ENTITY SPAWNER", url = "https://raw.githubusercontent.com/plamen6789/UtilitiesHub/main/UtilitiesGUI" },
    { gameName = "Doors", display = "King Hub", url = "https://pastebin.com/raw/R8QMbhzv" },
    { gameName = "Doors", display = "MSDOORS", url = "https://raw.githubusercontent.com/mstudio45/MSDOORS/main/MSDOORS.lua" },
    { gameName = "Doors", display = "Nerd Hub V3", url = "https://raw.githubusercontent.com/MrNeRD0/Doors-Hack/main/DoorsV3_ByNerd.lua" },
    { gameName = "Doors", display = "Nerd Hub V4", url = "https://raw.githubusercontent.com/MrNeRD0/Doors-Hack/main/doorsnerdv4.lua" },
    { gameName = "Doors", display = "Nerd Hub V5", url = "https://raw.githubusercontent.com/MrNeRD0/Doors-Hack/main/NeRDV5.lua" },
    { gameName = "Doors", display = "Poop Doors", url = "https://raw.githubusercontent.com/zoophiliaphobic/POOPDOORS/main/script.lua" },

    -- Evade
    { gameName = "Evade", display = "Darkrai-X", url = "https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/Evade" },
    { gameName = "Evade", display = "Evade", url = "https://raw.githubusercontent.com/9Strew/roblox/main/gamescripts/evade.lua" },
    { gameName = "Evade", display = "Evade Gui", url = "https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Evade/main.lua" },
    { gameName = "Evade", display = "Evade Tuperx", url = "https://raw.githubusercontent.com/TUPERX/TUPERX/Main/MenuBF/README.md" },
    { gameName = "Evade", display = "Hydra", url = "https://raw.githubusercontent.com/Robobo2022/script/main/Main.lua" },
    { gameName = "Evade", display = "Nex Hub", url = "https://raw.githubusercontent.com/CopyReal/NexHub/main/NexHubLoader" },
    { gameName = "Evade", display = "Project-WD", url = "https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Mainstring.lua" },
    { gameName = "Evade", display = "Real-King Evade", url = "https://raw.githubusercontent.com/zReal-King/Evade/main/Main.lua" },
    { gameName = "Evade", display = "Speed Evade", url = "https://raw.githubusercontent.com/Infinity2346/Tect-Menu/main/Speed.txt" },

    -- Grand Piece Online
    { gameName = "Grand Piece Online", display = "Lazer Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/lazer" },
    { gameName = "Grand Piece Online", display = "Xno Hub", url = "https://api.luarmor.net/files/v3/loaders/955dd3e8f43767eedf49f84ffac60170.lua" },
    { gameName = "Grand Piece Online", display = "Zephyrion Hub", url = "https://api.luarmor.net/files/v3/loaders/d2744abe1146d9accd91646050d082db.lua" },

    -- Haze Piece
    { gameName = "Haze Piece", display = "Beli Hunter", url = "https://raw.githubusercontent.com/1f0yt/community/main/Belihunter" },
    { gameName = "Haze Piece", display = "Hyper Hub", url = "https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua" },
    { gameName = "Haze Piece", display = "Legend HandlesYT", url = "https://raw.githubusercontent.com/LOLking123456/Haze/main/Piece" },
    { gameName = "Haze Piece", display = "Mystic Hub", url = "https://raw.githubusercontent.com/mo061/MysticHub/main/README.md" },
    { gameName = "Haze Piece", display = "Thunder Z", url = "https://raw.githubusercontent.com/ThundarZ/Welcome/main/Main/Loader/AllGame.lua" },
    { gameName = "Haze Piece", display = "Xtrey10x Hub", url = "https://raw.githubusercontent.com/xtrey10x/xtrey10x-hub/main/Haze%20Piece" },

    -- Jail Break
    { gameName = "Jail Break", display = "OneMoreHub", url = "https://gitlab.com/wspcontr/onemorehub/-/raw/main/scriptloader.lua" },
    { gameName = "Jail Break", display = "Project Auto", url = "https://raw.githubusercontent.com/Pxsta72/ProjectAuto/main/free" },
    { gameName = "Jail Break", display = "Sexsation", url = "https://api.luarmor.net/files/v3/loaders/730854e5b6499ee91deb1080e8e12ae3.lua" },
    { gameName = "Jail Break", display = "Vestra", url = "https://raw.githubusercontent.com/VestraTech/Vestra/main/Roblox/loader.lua" },

    -- Kat
    { gameName = "Kat", display = "Darkrai X", url = "https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/KAT" },
    { gameName = "Kat", display = "Darkyy Ware X", url = "https://raw.githubusercontent.com/AndrewDarkyy/NOWAY/main/darkyyware.lua" },
    { gameName = "Kat", display = "Kat Killer by JN HH Gaming", url = "https://raw.githubusercontent.com/JNHHGaming/Kat12/main/Kat" },
    { gameName = "Kat", display = "OwlHub", url = "https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt" },
    { gameName = "Kat", display = "SilentAim", url = "https://raw.githubusercontent.com/GamerScripter/nothing/main/sa" },
    { gameName = "Kat", display = "Unfair Hub", url = "https://raw.githubusercontent.com/rblxscriptsnet/unfair/main/rblxhub.lua" },

    -- King Legacy
    { gameName = "King Legacy", display = "BlackTrap", url = "https://blacktrap.org/blacktrap/users/checkpoint/Auth.txt" },
    { gameName = "King Legacy", display = "Hyper Hub", url = "https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua" },
    { gameName = "King Legacy", display = "Mukuro X Quartyz", url = "https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader" },
    { gameName = "King Legacy", display = "One X Hub", url = "https://raw.githubusercontent.com/xOne2/King-Legacy/main/README.md" },
    { gameName = "King Legacy", display = "Reaper Hub", url = "https://raw.githubusercontent.com/AyoReaper/Reaper-Hub/main/loader.lua" },
    { gameName = "King Legacy", display = "Speed Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Speed-Hub-X/main/SpeedHubX" },
    { gameName = "King Legacy", display = "ThunderZ", url = "https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader" },
    { gameName = "King Legacy", display = "Zen Hub", url = "https://raw.githubusercontent.com/Kaizenofficiall/ZenHub/main/Loader" },

    -- Legends Of Speed
    { gameName = "Legends Of Speed", display = "Arch", url = "https://raw.githubusercontent.com/lux933/Arch/main/Utilities/loader.lua" },
    { gameName = "Legends Of Speed", display = "Code Hub", url = "https://raw.githubusercontent.com/coder382/CodeHub/main/Loader.lua" },
    { gameName = "Legends Of Speed", display = "Cryo Hub", url = "https://raw.githubusercontent.com/CryoScript/Scripts.lua/main/Legends%20of%20Speed.lua" },
    { gameName = "Legends Of Speed", display = "Legends Of Speed 1", url = "https://raw.githubusercontent.com/WhackyCode/SPEEDDEVIL/main/legendsofspeed.lua" },
    { gameName = "Legends Of Speed", display = "Legends Of Speed 2", url = "https://raw.githubusercontent.com/YukiTM/Roblox/main/Legends" },
    { gameName = "Legends Of Speed", display = "Legends Of Speed 3", url = "https://raw.githubusercontent.com/StupidProAArsenal/main/main/Legenos%20of%20speedos" },
    { gameName = "Legends Of Speed", display = "Legends Of Speed Rayfield", url = "https://pastebin.com/raw/wGjDdXNX" },
    { gameName = "Legends Of Speed", display = "Legends Of Speed by Waza80", url = "https://raw.githubusercontent.com/GamerScripter/nothing/main/los" },
    { gameName = "Legends Of Speed", display = "Pog Hub No Carte", url = "https://raw.githubusercontent.com/03koios/Loader/main/Loader.lua" },
    { gameName = "Legends Of Speed", display = "Project L", url = "https://raw.githubusercontent.com/IsThisMe01/Project-L/main/LegendsOfSpeed.lua" },
    { gameName = "Legends Of Speed", display = "Project Meow", url = "https://scriptblox.com/raw/Legends-Of-Speed-Speeeeed-Farm-Open-Source-old-code-lel-1785" },
    { gameName = "Legends Of Speed", display = "Project Omega", url = "https://raw.githubusercontent.com/TheScriptPirate/ProjectOmega/main/ProjectOmegaLoader.lua" },
    { gameName = "Legends Of Speed", display = "Proxima Hub", url = "https://raw.githubusercontent.com/TrixAde/Proxima-Hub/main/Main.lua" },
    { gameName = "Legends Of Speed", display = "Pss Hub", url = "https://raw.githubusercontent.com/psswaldo/psshub/main/main.lua" },
    { gameName = "Legends Of Speed", display = "Sky Hub", url = "https://raw.githubusercontent.com/arlists/Sky-Hub/main/Main" },
    { gameName = "Legends Of Speed", display = "Speed Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Speed-Hub-X/main/SpeedHubX" },
    { gameName = "Legends Of Speed", display = "SuPray", url = "https://raw.githubusercontent.com/LiverMods/SuPray/main/Speed-of-Legends.lua" },
    { gameName = "Legends Of Speed", display = "Tbao Hub", url = "https://raw.githubusercontent.com/tbao143/thaibao/main/TbaoHublegendsofspeed" },
    { gameName = "Legends Of Speed", display = "Uciha Hub", url = "https://raw.githubusercontent.com/fareljr1/Hub/main/Loader" },
    { gameName = "Legends Of Speed", display = "Vynixius", url = "https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Legends%20Of%20Speed/Script.lua" },
    { gameName = "Legends Of Speed", display = "Weinz", url = "https://raw.githubusercontent.com/weiny-ez/w-main/main/loader.lua" },

    -- Mad City
    { gameName = "Mad City", display = "ProBacon Hub", url = "https://raw.githubusercontent.com/aymarko/ProBaconHub/main/probacon1234/aymarko/MadCity/GUI/Beta" },
    { gameName = "Mad City", display = "Ruby Hub Free", url = "https://raw.githubusercontent.com/Deni210/madcity/main/Ruby%20Hub%20Chapter%202" },
    { gameName = "Mad City", display = "Ruby Hub v2.0", url = "https://raw.githubusercontent.com/Deni210/madcity/main/Ruby%20Hub%20v1.1" },

    -- Murder Mystery 2
    { gameName = "Murder Mystery 2", display = "Auto Coin", url = "https://raw.githubusercontent.com/tvgueimer84/tvgueimerr23232/main/mmm2" },
    { gameName = "Murder Mystery 2", display = "Dreadz Hub", url = "https://raw.githubusercontent.com/DreadzHub2/DreadzHub-Scripts-FR/main/Loader" },
    { gameName = "Murder Mystery 2", display = "Eclipse Hub", url = "https://api.eclipsehub.xyz/auth" },
    { gameName = "Murder Mystery 2", display = "Ghost Hub", url = "https://raw.githubusercontent.com/GhostPlayer352/Test4/main/GhostHub" },
    { gameName = "Murder Mystery 2", display = "Highlight Hub", url = "https://raw.githubusercontent.com/ThatSick/HighlightMM2/main/Free" },
    { gameName = "Murder Mystery 2", display = "Jayy Hub", url = "https://raw.githubusercontent.com/reed192512/jayyhubcloud/main/MainLoadstring" },
    { gameName = "Murder Mystery 2", display = "Kidachi Hub", url = "https://raw.githubusercontent.com/KidichiHB/Kidachi/main/Scripts/MM2_V2" },
    { gameName = "Murder Mystery 2", display = "Lunar Hub", url = "https://raw.githubusercontent.com/vwSaraa/LunarHub/main/mm2" },
    { gameName = "Murder Mystery 2", display = "Murder Mystery 2", url = "https://raw.githubusercontent.com/danielontopp/scripts/main/mm2" },
    { gameName = "Murder Mystery 2", display = "Murder Mystery 2 by:ScriptX Version X", url = "https://raw.githubusercontent.com/JunBloxYTPlayz/SORIX-Hub/main/Murder%20Mystery%202%20Version%20X" },
    { gameName = "Murder Mystery 2", display = "Nexus Hub", url = "https://raw.githubusercontent.com/13B8B/NEXUS/main/loadstring" },
    { gameName = "Murder Mystery 2", display = "R3th Priv", url = "https://raw.githubusercontent.com/R3TH-PRIV/R3TH-PRIV/main/LOAD.lua" },
    { gameName = "Murder Mystery 2", display = "Ski Hub", url = "https://pastebin.com/raw/203DBjLx" },
    { gameName = "Murder Mystery 2", display = "Symphony Hub", url = "https://itsjidy.github.io/SymphonyHub/Loader.html" },

    -- Murderers Vs Sheriffs
    { gameName = "Murderers Vs Sheriffs", display = "Bebo Scripts", url = "https://raw.githubusercontent.com/Bebo-Mods/BeboScripts/main/MurderersVsSheriffs.lua" },
    { gameName = "Murderers Vs Sheriffs", display = "Emptyness Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/EmptynessNoBlur" },
    { gameName = "Murderers Vs Sheriffs", display = "Kenniel Script", url = "https://raw.githubusercontent.com/Kenniel123/Murderers-VS-Sheriffs-Duels-script/main/Murderers%20VS%20Sheriffs%20Duels%20script" },
    { gameName = "Murderers Vs Sheriffs", display = "Legend HandlesYT", url = "https://raw.githubusercontent.com/LOLking123456/Duels7/main/Sheriffs56" },
    { gameName = "Murderers Vs Sheriffs", display = "Muderer Vs Sheriff", url = "https://raw.githubusercontent.com/GamerScripter/nothing/main/mvs" },
    { gameName = "Murderers Vs Sheriffs", display = "Oasis Hub", url = "https://raw.githubusercontent.com/bruvzz/oasishub/main/script" },
    { gameName = "Murderers Vs Sheriffs", display = "Ranxware", url = "https://raw.githubusercontent.com/AsteriskCodes/Ranxware-V2-Restored/main/source.lua" },
    { gameName = "Murderers Vs Sheriffs", display = "Ro Flux Hub", url = "https://roflux.net/scripts/games/" .. tostring(game.PlaceId) .. ".lua" },
    { gameName = "Murderers Vs Sheriffs", display = "Ruby Hub", url = "https://raw.githubusercontent.com/Deni210/murdersvssherrifsduels/main/rubyhub" },

    -- My Restaurant
    { gameName = "My Restaurant", display = "Milk Up", url = "https://pastebin.com/raw/uBpUr2vU" },
    { gameName = "My Restaurant", display = "My Restaurant", url = "https://raw.githubusercontent.com/scriptpastebin/raw/main/MyRestaurant" },
    { gameName = "My Restaurant", display = "Project Lightning", url = "https://raw.githubusercontent.com/ProjectLightningDev/Project-Lightning-Loader/main/Loader.Lua" },
    { gameName = "My Restaurant", display = "Project WD", url = "https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Mainstring.lua" },
    { gameName = "My Restaurant", display = "Rafa Hub", url = "https://raw.githubusercontent.com/Rafacasari/roblox-scripts/main/mr.lua" },
    { gameName = "My Restaurant", display = "Wyn's Script", url = "https://system-exodus.com/scripts/MyRestaurant/MyRestaurant.lua" },

    -- Natural Disaster Survival
    { gameName = "Natural Disaster Survival", display = "Binary Hub", url = "https://raw.githubusercontent.com/BinaryHubOfficial/binaryhub/main/init.lua" },
    { gameName = "Natural Disaster Survival", display = "CH Hub", url = "https://raw.githubusercontent.com/RobloxHackingProject/CHHub/main/CHHub.lua" },
    { gameName = "Natural Disaster Survival", display = "Dark Ware", url = "https://raw.githubusercontent.com/Yarik312/DarkWare/main/MainLoader" },
    { gameName = "Natural Disaster Survival", display = "Eclipse Hub", url = "https://api.eclipsehub.xyz/auth" },
    { gameName = "Natural Disaster Survival", display = "Natural Disaster Hub", url = "https://raw.githubusercontent.com/hussain1323232234/My-Scripts/main/Natural%20Disaster" },
    { gameName = "Natural Disaster Survival", display = "Natural Disaster Survival By:RIP", url = "https://raw.githubusercontent.com/CasperFlyModz/discord.gg-rips/main/NaturalDisasterSurvival.lua" },
    { gameName = "Natural Disaster Survival", display = "NDS_A'X", url = "https://raw.githubusercontent.com/Bac0nh1ck/Scripts/main/NDS_A%5EX" },
    { gameName = "Natural Disaster Survival", display = "NDS Hub", url = "https://raw.githubusercontent.com/9NLK7/93qjoadnlaknwldk/main/main" },
    { gameName = "Natural Disaster Survival", display = "NDS GUI", url = "https://raw.githubusercontent.com/2dgeneralspam1/scripts-and-stuff/master/scripts/LoadstringUjHI6RQpz2o8" },
    { gameName = "Natural Disaster Survival", display = "Rawnder", url = "https://raw.githubusercontent.com/LiverMods/Rawnder-NTDR/main/NaturalDisaster" },
    { gameName = "Natural Disaster Survival", display = "Six Hub", url = "https://raw.githubusercontent.com/ySixxNz/Natural-Desastre/Main/EN%20Language" },
    { gameName = "Natural Disaster Survival", display = "Zeerox Hub", url = "https://raw.githubusercontent.com/RunDTM/ZeeroxHub/main/Loader.lua" },

    -- Nico Nextbot
    { gameName = "Nico Nextbot", display = "Darkrai-X", url = "https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/NicoNextBots" },
    { gameName = "Nico Nextbot", display = "Hp Hub", url = "https://raw.githubusercontent.com/RobloxHackingProject/HPHub/main/HPHub.lua" },
    { gameName = "Nico Nextbot", display = "NexHub", url = "https://raw.githubusercontent.com/CopyReal/NexHub/main/NexHubLoader" },
    { gameName = "Nico Nextbot", display = "Nico NextBot", url = "https://pastebin.com/raw/DFfKb4i9" },
    { gameName = "Nico Nextbot", display = "WercT", url = "https://raw.githubusercontent.com/dropouut/Shindai/main/wercT.lua" },

    -- Pet Catchers
    { gameName = "Pet Catchers", display = "Banana Hub", url = "https://raw.githubusercontent.com/diepedyt/bui/main/newMainKeySytem.lua" },
    { gameName = "Pet Catchers", display = "GatoHub", url = "https://raw.githubusercontent.com/Catto-YFCN/GatoHub/main/PetCatchers" },
    { gameName = "Pet Catchers", display = "Huge Games", url = "https://api.luarmor.net/files/v3/loaders/f38c17c4a5e9f38a7dac14ce0940688d.lua" },
    { gameName = "Pet Catchers", display = "IdiotHub", url = "https://raw.githubusercontent.com/IdiotHub/Scripts/main/Pet%20Catcher/Pet%20Catchers%20Main" },
    { gameName = "Pet Catchers", display = "Lenut Hub", url = "https://raw.githubusercontent.com/lenutjr/pc/main/petcatchers" },
    { gameName = "Pet Catchers", display = "Nexus Hub", url = "https://raw.githubusercontent.com/CrazyHub123/NexusHubMain/main/Main.lua" },
    { gameName = "Pet Catchers", display = "Pet Catchers", url = "https://raw.githubusercontent.com/Marco8642/science/main/PET%20CATCHERS" },

    -- Pet Simulator 99
    { gameName = "Pet Simulator 99", display = "Auto Stairway To Heaven", url = "https://raw.githubusercontent.com/fissurectomy/woah/main/ps99_stairway.lua" },
    { gameName = "Pet Simulator 99", display = "Banana Hub", url = "https://raw.githubusercontent.com/diepedyt/bui/main/newMainKeySytem.lua" },
    { gameName = "Pet Simulator 99", display = "Huge Games", url = "https://hugegames.io/ps99" },
    { gameName = "Pet Simulator 99", display = "Idiot Hub", url = "https://raw.githubusercontent.com/Somerandomidiot/Lua/main/PS99_Protected.txt" },
    { gameName = "Pet Simulator 99", display = "Legend HandlesYT", url = "https://raw.githubusercontent.com/LOLking123456/Sim2/main/Pet99" },
    { gameName = "Pet Simulator 99", display = "REDz HUB", url = "https://raw.githubusercontent.com/REDzHUB/PetSimulator99/main/redz9999.lua" },
    { gameName = "Pet Simulator 99", display = "Sky Hub", url = "https://raw.githubusercontent.com/SKOIXLL/RIVERHUB-SKYHUB/main/WL.lua" },
    { gameName = "Pet Simulator 99", display = "Syrex Hub", url = "https://syrexhub.netlify.app/raw/petsimulator99/syrexhub" },
    { gameName = "Pet Simulator 99", display = "Zekrom Hub X", url = "https://raw.githubusercontent.com/ahmadsgamer2/Zekrom-Hub-X/main/Zekrom-Hub-X-exe" },
    { gameName = "Pet Simulator 99", display = "Zer0 Hub", url = "https://raw.githubusercontent.com/Discord0000/Zer0Hub/main/MainScript.lua" },

    -- Pet Simulator X
    { gameName = "Pet Simulator X", display = "BlackTrap", url = "https://blacktrap.org/blacktrap/users/checkpoint/Auth.txt" },
    { gameName = "Pet Simulator X", display = "Catalyst", url = "https://raw.githubusercontent.com/destylol/catalyst/itachi/main.lua" },
    { gameName = "Pet Simulator X", display = "Cloud Hub", url = "https://raw.githubusercontent.com/BadScripters/CloudHub/main/hub" },
    { gameName = "Pet Simulator X", display = "Extreme Hub", url = "https://raw.githubusercontent.com/ExtremeAntonis/KeySystemUI/main/All-Scripts-Obfuscated.lua" },
    { gameName = "Pet Simulator X", display = "EVO V4", url = "https://projectevo.xyz/v4/script.lua" },
    { gameName = "Pet Simulator X", display = "Huge Games", url = "https://hugegames.io/psx" },
    { gameName = "Pet Simulator X", display = "Milk Up", url = "https://api.luarmor.net/files/v3/loaders/2a31571481d9db7f3be01903493bfc9a.lua" },
    { gameName = "Pet Simulator X", display = "Project WD", url = "https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Mainstring.lua" },
    { gameName = "Pet Simulator X", display = "Rafa Hub", url = "https://raw.githubusercontent.com/Rafacasari/roblox-scripts/main/psx.lua" },
    { gameName = "Pet Simulator X", display = "Rblx Hub", url = "https://paste.xyzo.space/rblxhub/all.lua" },
    { gameName = "Pet Simulator X", display = "ThunderZ(PC)", url = "https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader" },

    -- Prison Life
    { gameName = "Prison Life", display = "Astral Hub", url = "https://raw.githubusercontent.com/Vcsk/AstralHub/main/Games/PrisonLife/main.lua" },
    { gameName = "Prison Life", display = "Del Hub", url = "https://pastebin.com/raw/QY07DaJS" },
    { gameName = "Prison Life", display = "Fe Btools", url = "https://rawscripts.net/raw/Universal-Script-Fe-btools-script-for-prison-life-9706" },
    { gameName = "Prison Life", display = "Fe Disabled Tool Gui", url = "https://pastebin.com/raw/AZVi2tuK" },
    { gameName = "Prison Life", display = "Juanko", url = "https://pastebin.com/raw/rfAULQ83" },
    { gameName = "Prison Life", display = "Moonlight", url = "https://raw.githubusercontent.com/ObviouslyOrchi/Prison-life/main/Moonlight%20Client%20Prison%20Life" },
    { gameName = "Prison Life", display = "Tiger Admin", url = "https://raw.githubusercontent.com/H17S32/Tiger_Admin/main/Script" },
    { gameName = "Prison Life", display = "Vynixius", url = "https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Prison%20Life/Prison%20Life" },

    -- Project Mugetsu
    { gameName = "Project Mugetsu", display = "JumbleScripts", url = "https://jumblescripts.com/ProjectMugetsu.lua" },
    { gameName = "Project Mugetsu", display = "Pm", url = "https://raw.githubusercontent.com/TrickyAH/Scripts/main/loader.lua" },
    { gameName = "Project Mugetsu", display = "Purple Hub", url = "https://raw.githubusercontent.com/TheyCallMeVox/scripts/main/PM" },
    { gameName = "Project Mugetsu", display = "Valynium", url = "https://raw.githubusercontent.com/XO-3S-CL-VCK-jf-3HDM/Products/main/Project-Mugetsu.lua" },
    { gameName = "Project Mugetsu", display = "Verny Hub V2", url = "https://raw.githubusercontent.com/666dasdlolok/VernyHubV2/main/Main" },

    -- Project Slayer
    { gameName = "Project Slayer", display = "Nuke Hub", url = "https://raw.githubusercontent.com/NukeVsCity/Scripts2023/main/projslayerthingy" },
    { gameName = "Project Slayer", display = "Oni Hub", url = "https://api.luarmor.net/files/v3/loaders/01471f12f9adfd4537f4cc0b3b7bba14.lua" },
    { gameName = "Project Slayer", display = "Shark Hub", url = "https://pastebin.com/raw/TcbS1i6E" },
    { gameName = "Project Slayer", display = "Skeered Hub", url = "https://raw.githubusercontent.com/Skeereddo/name/main/krnl" },
    { gameName = "Project Slayer", display = "Sylveon Hub", url = "https://raw.githubusercontent.com/ogamertv12/SylveonHub/main/Mobile.lua" },
    { gameName = "Project Slayer", display = "Versaware Hub", url = "https://raw.githubusercontent.com/asterionnn/versaware_free/main/VersawareFree.lua" },
    { gameName = "Project Slayer", display = "Zyrc Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/mugentr" },

    -- Punch Simulator
    { gameName = "Punch Simulator", display = "Angeel Hub", url = "https://raw.githubusercontent.com/Angeelvxg/PunchSimulator/main/PunchSimulator.lua" },
    { gameName = "Punch Simulator", display = "Blue GUI", url = "https://raw.githubusercontent.com/JustAP1ayer/PlayerHubOther/main/PlayerHubPunchingSimulator.lua" },
    { gameName = "Punch Simulator", display = "Perfectus Hub", url = "https://raw.githubusercontent.com/PerfectusMim/dbevo/main/asfasfasfasf" },
    { gameName = "Punch Simulator", display = "Tora Hub", url = "https://raw.githubusercontent.com/ToraIsMe/ToraIsMe/main/0PUNCH" },

    -- Punch Wall Simulator
    { gameName = "Punch Wall Simulator", display = "Codexus Trial", url = "https://raw.githubusercontent.com/Bebo-Mods/BeboScripts/main/PunchWallSim.lua" },
    { gameName = "Punch Wall Simulator", display = "ImperorLegend Hub", url = "https://raw.githubusercontent.com/ImperorLegend/Orig-PWSim-Script/main/Script" },
    { gameName = "Punch Wall Simulator", display = "Nexus", url = "https://raw.githubusercontent.com/F2B-HUB/F2B/main/HUB" },
    { gameName = "Punch Wall Simulator", display = "Platinium Hub", url = "https://raw.githubusercontent.com/ZaRdoOx/Loader/main/PlatiniumLoader" },
    { gameName = "Punch Wall Simulator", display = "Punch Wall Simulator", url = "https://raw.githubusercontent.com/momentBr/game-script/main/Punch%20Wall%20Simulator" },
    { gameName = "Punch Wall Simulator", display = "Punch Wall Simulator YT ToraIsMe", url = "https://raw.githubusercontent.com/ToraIsMe/ToraIsMe/main/0punch" },
    { gameName = "Punch Wall Simulator", display = "Yoto Hub", url = "https://raw.githubusercontent.com/Binintrozza/GUI-SCRIPT/main/Main" },

    -- Rainbow Friends (Chapter 2)
    { gameName = "Rainbow Friends", display = "BorkWare", url = "https://raw.githubusercontent.com/Ihaveash0rtnamefordiscord/BorkWare/main/Scripts/" .. game.GameId .. ".lua" },
    { gameName = "Rainbow Friends", display = "Frightened Hub", url = "https://raw.githubusercontent.com/Nicuse/FrightenedHub/main/Loader.lua" },
    { gameName = "Rainbow Friends", display = "Rainbow Friends KEPA", url = "https://raw.githubusercontent.com/Keparetiolpxe/rbxscript/main/RainbowFriendsKEPA" },
    { gameName = "Rainbow Friends", display = "Rainbow Friends", url = "https://pastebin.com/raw/yVhAwibN" },
    { gameName = "Rainbow Friends", display = "ToraIsMe", url = "https://raw.githubusercontent.com/ToraIsMe/ToraIsMe/main/0rainbow" },
    { gameName = "Rainbow Friends", display = "Voidz", url = "https://raw.githubusercontent.com/RTrade/Voidz/main/Games.lua" },

    -- Shadow Boxing
    { gameName = "Shadow Boxing", display = "Flare Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/ShadowBoxing" },
    { gameName = "Shadow Boxing", display = "Trey's Hub", url = "https://raw.githubusercontent.com/xtrey10x/xtrey10x-hub/main/shadow" },

    -- Slap Battles
    { gameName = "Slap Battles", display = "CherryUI's Hub", url = "https://raw.githubusercontent.com/RandomScriptr3/gggggggg/main/lolez.txt" },
    { gameName = "Slap Battles", display = "Dizzy Hub", url = "https://raw.githubusercontent.com/dizyhvh/rbx_scripts/main/dizzy_hub/scripts/slap_battles.lua" },
    { gameName = "Slap Battles", display = "Hub That Exists", url = "https://raw.githubusercontent.com/ionlyusegithubformcmods/1-Line-Scripts/main/Slap%20Battles" },
    { gameName = "Slap Battles", display = "Infinite Ware", url = "https://raw.githubusercontent.com/Blackie-coke/InfiniteWare/main/KS.lua" },
    { gameName = "Slap Battles", display = "Purple R20 Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/anakinn" },
    { gameName = "Slap Battles", display = "Slap Battle Gui", url = "https://raw.githubusercontent.com/dizyhvh/slap_battles_gui/main/0.lua" },
    { gameName = "Slap Battles", display = "R20-Exploiter", url = "https://raw.githubusercontent.com/cheesynob39/R2O/main/LOADSTRING.lua" },
    { gameName = "Slap Battles", display = "Vantra Hub", url = "https://vantra.cc/api/script/get?placeid=MainLoader" },
    { gameName = "Slap Battles", display = "Whopper", url = "https://raw.githubusercontent.com/qwertyui-cool/uhh-yes/main/whopper.lua" },

    -- Sol's RNG
    { gameName = "Sol's RNG", display = "HoHo Hub", url = "https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI" },
    { gameName = "Sol's RNG", display = "Legend Handless Hub", url = "https://raw.githubusercontent.com/LOLking123456/upd/main/rng" },
    { gameName = "Sol's RNG", display = "Sol's RNG", url = "https://raw.githubusercontent.com/Toilet71/Games-Sol-s/main/Sol's%20Script" },
    { gameName = "Sol's RNG", display = "Sols RNG Panel", url = "https://raw.githubusercontent.com/Looser3itx/Hmmmmmmmmmmmmmmmmmmmmmmmmmmmm/main/loader.lua" },

    -- Sonic Speed Simulator
    { gameName = "Sonic Speed Simulator", display = "Cheater Soul", url = "https://raw.githubusercontent.com/Luciquad/credit/main/sonicspeedsimulator.lua" },
    { gameName = "Sonic Speed Simulator", display = "Master Hub", url = "https://raw.githubusercontent.com/destylol/masterhubv311/itachi/Main.lua" },
    { gameName = "Sonic Speed Simulator", display = "Skays", url = "https://rawscripts.net/raw/Universal-Script-SkaysGG-2095" },
    { gameName = "Sonic Speed Simulator", display = "Sonic Speed Simulator", url = "https://raw.githubusercontent.com/kkeyy-hash/roblox/main/SonicSpeedSimulator2.lua" },

    -- The Strongest Battlegrounds
    { gameName = "The Strongest Battlegrounds", display = "Hawk Hub", url = "https://raw.githubusercontent.com/TheHanki/Hawk/main/Loader" },
    { gameName = "The Strongest Battlegrounds", display = "Nex Hub", url = "https://raw.githubusercontent.com/CopyReal/NexHub/main/NexHubLoader" },
    { gameName = "The Strongest Battlegrounds", display = "Nicuse Hub", url = "https://raw.githubusercontent.com/Nicuse/RobloxScripts/main/SaitamaBattlegrounds.lua" },
    { gameName = "The Strongest Battlegrounds", display = "LOLking123456", url = "https://raw.githubusercontent.com/LOLking123456/battleground1/main/Saitama41" },
    { gameName = "The Strongest Battlegrounds", display = "Xtrey10x Hub", url = "https://raw.githubusercontent.com/xtrey10x/xtrey10x-hub/main/saitama" },

    -- Tower Of Hell
    { gameName = "Tower Of Hell", display = "Admin", url = "https://raw.githubusercontent.com/TwomadJR/nto/main/admiin" },
    { gameName = "Tower Of Hell", display = "Eclipse Hub", url = "https://api.eclipsehub.xyz/auth" },
    { gameName = "Tower Of Hell", display = "Floater Scripts", url = "https://raw.githubusercontent.com/iiProductionz/Floater-Scripts/main/WaifuEdition/Tower%20Of%20Hell" },
    { gameName = "Tower Of Hell", display = "Garfield Hub", url = "https://raw.githubusercontent.com/2dgeneralspam1/scripts-and-stuff/master/scripts/garfield%20hub" },
    { gameName = "Tower Of Hell", display = "LighTux", url = "https://raw.githubusercontent.com/zeuise0002/SSSWWW222/main/README.md" },
    { gameName = "Tower Of Hell", display = "Tower Of Hell Gui", url = "https://gist.githubusercontent.com/BloxiYT/85f97364b6367baac677e109488c9905/raw/c2972a2b892c4193509ddb2fe1ba3061435e1a8a/gistfile1.txt" },
    { gameName = "Tower Of Hell", display = "Tower Of Hell Gui by:The Mystery O_O", url = "https://pastebin.com/raw/BbVHjH56" },

    -- UnderGround War
    { gameName = "UnderGround War", display = "Multi Hub", url = "https://raw.githubusercontent.com/jj123llol/multi-hub/main/Multi" },
    { gameName = "UnderGround War", display = "Unique Hub", url = "https://raw.githubusercontent.com/jynzl/UniqueHub/main/UniqueHubv2Intro" },
    { gameName = "UnderGround War", display = "UnderGround War Gui", url = "https://pastebin.com/raw/iuqYjEAX" },
    { gameName = "UnderGround War", display = "UnderGround War 1", url = "https://raw.githubusercontent.com/GhostPlayer352/Test4/main/The%20UnderGround%20War%203" },

    -- Wisteria 2
    { gameName = "Wisteria 2", display = "Flare Hub", url = "https://raw.githubusercontent.com/1f0yt/community/main/wisteria2script" },
    { gameName = "Wisteria 2", display = "Jumble Hub", url = "https://jumblescripts.com/JumbleHub.lua" },
    { gameName = "Wisteria 2", display = "Kidachi Hub", url = "https://raw.githubusercontent.com/KidichiHB/Kidachi/main/Scripts/Wisteria" },

    -- Your Bizarre Adventure
    { gameName = "Your Bizarre Adventure", display = "CuHub V3", url = "https://raw.githubusercontent.com/ItachiPvPUchiha/CuHub/main/yba.lua" },
    { gameName = "Your Bizarre Adventure", display = "Green Gui B-Boy", url = "https://raw.githubusercontent.com/zakater5/LuaRepo/main/YBA/v3.lua" },
    { gameName = "Your Bizarre Adventure", display = "Gui by Death", url = "https://raw.githubusercontent.com/VoidGaster/Scripts/main/" .. tostring(game.PlaceId) },
    { gameName = "Your Bizarre Adventure", display = "Midnight Hub", url = "https://raw.githubusercontent.com/TheFarowHywolf/YBA-Midnight-script/master/YBA.lua" },

    -- 3008
    { gameName = "3008", display = "CheatX", url = "https://raw.githubusercontent.com/GamerScripter/nothing/main/3008" },
    { gameName = "3008", display = "God Mode", url = "https://raw.githubusercontent.com/CHnamedata/WhatDaHeck/main/3008GodMode.lua" },
    { gameName = "3008", display = "V.G Hub", url = "https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub" }
}